In [1]:
from sklearn import datasets


# Loading data


In [2]:
iris=datasets.load_iris()
digits=datasets.load_digits()

In [3]:
print(iris.data)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [4]:
list(iris.target)

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]

In [5]:
list(iris.target_names)

['setosa', 'versicolor', 'virginica']

In [6]:
iris.data.shape

(150, 4)

In [7]:
#above tasks are practice

In [8]:
#New practice

In [9]:
#http://machinelearningmastery.com/machine-learning-in-python-step-by-step/

In [10]:
#visit that link for below description


In [1]:
# Check the versions of libraries

# Python version
import sys
print('Python: {}'.format(sys.version))
# scipy
import scipy
print('scipy: {}'.format(scipy.__version__))
# numpy
import numpy
print('numpy: {}'.format(numpy.__version__))
# matplotlib
import matplotlib
print('matplotlib: {}'.format(matplotlib.__version__))
# pandas
import pandas
print('pandas: {}'.format(pandas.__version__))
# scikit-learn
import sklearn
print('sklearn: {}'.format(sklearn.__version__))

Python: 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
scipy: 0.18.1
numpy: 1.11.1
matplotlib: 1.5.3
pandas: 0.18.1
sklearn: 0.18.1


In [2]:
# Load libraries
import pandas
from pandas.tools.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [3]:
# Load dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pandas.read_csv(url, names=names)

In [4]:
# shape
print(dataset.shape)

(150, 5)


In [5]:
# head
print(dataset.head(20))

    sepal-length  sepal-width  petal-length  petal-width        class
0            5.1          3.5           1.4          0.2  Iris-setosa
1            4.9          3.0           1.4          0.2  Iris-setosa
2            4.7          3.2           1.3          0.2  Iris-setosa
3            4.6          3.1           1.5          0.2  Iris-setosa
4            5.0          3.6           1.4          0.2  Iris-setosa
5            5.4          3.9           1.7          0.4  Iris-setosa
6            4.6          3.4           1.4          0.3  Iris-setosa
7            5.0          3.4           1.5          0.2  Iris-setosa
8            4.4          2.9           1.4          0.2  Iris-setosa
9            4.9          3.1           1.5          0.1  Iris-setosa
10           5.4          3.7           1.5          0.2  Iris-setosa
11           4.8          3.4           1.6          0.2  Iris-setosa
12           4.8          3.0           1.4          0.1  Iris-setosa
13           4.3    

In [6]:
# descriptions
print(dataset.describe())

       sepal-length  sepal-width  petal-length  petal-width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


In [7]:
# class distribution
print(dataset.groupby('class').size())

class
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
dtype: int64


In [1]:
print(dataset.values)

NameError: name 'dataset' is not defined

In [2]:
print(dataset.shape)

NameError: name 'dataset' is not defined

In [1]:
pip install --upgrade --no-cache-dir https://get.graphlab.com/GraphLab-Create/2.1/sathishp.railway2@gmail.com/A85C-B740-348A-699E-8277-66D9-199C-460C/GraphLab-Create-License.tar.gz

SyntaxError: invalid syntax (<ipython-input-1-7cbc43185436>, line 1)

In [2]:
dataset.head

NameError: name 'dataset' is not defined

In [3]:
url="https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

In [4]:
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pandas.read_csv(url, names=names)

NameError: name 'pandas' is not defined

In [5]:
import pandas


In [6]:
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pandas.read_csv(url, names=names)

In [7]:
from pandas.tools.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC


In [8]:
dataset.shape


(150, 5)

In [9]:
dataset.head

<bound method NDFrame.head of      sepal-length  sepal-width  petal-length  petal-width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
5             5.4          3.9           1.7          0.4     Iris-setosa
6             4.6          3.4           1.4          0.3     Iris-setosa
7             5.0          3.4           1.5          0.2     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
9             4.9          3.1           1.5          0.1     Iris-setosa
10            5.4          3.7           1.5          0.2     Iris-setosa
11            4.8          3.4           1.6          0.2     Iris-setosa
12      

In [10]:
print(dataset.head(30))

    sepal-length  sepal-width  petal-length  petal-width        class
0            5.1          3.5           1.4          0.2  Iris-setosa
1            4.9          3.0           1.4          0.2  Iris-setosa
2            4.7          3.2           1.3          0.2  Iris-setosa
3            4.6          3.1           1.5          0.2  Iris-setosa
4            5.0          3.6           1.4          0.2  Iris-setosa
5            5.4          3.9           1.7          0.4  Iris-setosa
6            4.6          3.4           1.4          0.3  Iris-setosa
7            5.0          3.4           1.5          0.2  Iris-setosa
8            4.4          2.9           1.4          0.2  Iris-setosa
9            4.9          3.1           1.5          0.1  Iris-setosa
10           5.4          3.7           1.5          0.2  Iris-setosa
11           4.8          3.4           1.6          0.2  Iris-setosa
12           4.8          3.0           1.4          0.1  Iris-setosa
13           4.3    

In [11]:
print(dataset.head(150))

     sepal-length  sepal-width  petal-length  petal-width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
5             5.4          3.9           1.7          0.4     Iris-setosa
6             4.6          3.4           1.4          0.3     Iris-setosa
7             5.0          3.4           1.5          0.2     Iris-setosa
8             4.4          2.9           1.4          0.2     Iris-setosa
9             4.9          3.1           1.5          0.1     Iris-setosa
10            5.4          3.7           1.5          0.2     Iris-setosa
11            4.8          3.4           1.6          0.2     Iris-setosa
12            4.8          3.0        

# Creating a Comment
 
 ## This will be a sub comment 
 * this is a sub ka sub comment
 * take this bitch
 * yo yo

In [1]:
import pandas
from pandas.tools.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [2]:
# Load dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pandas.read_csv(url, names=names)

## Fuctions in python


In [3]:
square = lambda x:x*x

In [4]:
square(3)

9

In [5]:
greater = lambda x,y: x+y

In [6]:
greater(3,7)

10

In [8]:
compare= lambda x,y: x>y

# testing it

hi

In [9]:
compare(2,3)

False

In [10]:
compare(6,4)

True

In [1]:
import sklearn

In [2]:
features=[[140,1],[135,1],[155,0],[150,0]]

In [3]:
label=[1,1,0,0]

In [4]:
from sklearn import tree

In [5]:
clf=tree.DecisionTreeClassifier()

In [6]:
clf=clf.fit(features,label)

In [9]:
print(clf.predict([[140,1]]))

[1]


In [1]:
from sklearn import tree

In [11]:
features=[[48,0],[25,0],[89,1],[75,1],[50,1],[60,1],[15,0]]

In [7]:
label1=[0,0,1,1,1,1,0]

In [4]:
clk=tree.DecisionTreeClassifier()

In [12]:
clk=clk.fit(features,label1)

In [14]:
print(clk.predict([[51,1]]))

[1]


In [1]:
import graphlab


ACTION REQUIRED: Dependencies libstdc++-6.dll and libgcc_s_seh-1.dll not found.

1. Ensure user account has write permission to C:\Users\user\Anaconda3\envs\gl-env\lib\site-packages\graphlab
2. Run graphlab.get_dependencies() to download and install them.
3. Restart Python and import graphlab again.

By running the above function, you agree to the following licenses.

* libstdc++: https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html
* xz: http://git.tukaani.org/?p=xz.git;a=blob;f=COPYING
    


In [2]:
graphlab.get_dependencies()


By running this function, you agree to the following licenses.

* libstdc++: https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html
* xz: http://git.tukaani.org/?p=xz.git;a=blob;f=COPYING
    
Extracting xz.


ContentTooShortError: retrieval incomplete: got only 381980 out of 546800 bytes

In [ ]:
import graphlab

# loading data


nfwsf


In [3]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']


In [2]:
import graphlab


In [6]:
data=graphlab.SFrame('iris.csv')

Finished parsing file C:\Users\user\Documents\Python Scripts\iris.csv

Parsing completed. Parsed 99 lines in 0.021002 secs.

------------------------------------------------------
Inferred types from first 100 line(s) of file as 
column_type_hints=[float,float,float,float,float,float,float,float,str]
If parsing fails due to incorrect types, you can correct
the inferred type list above and pass it to read_csv in
the column_type_hints argument
------------------------------------------------------


Finished parsing file C:\Users\user\Documents\Python Scripts\iris.csv

Parsing completed. Parsed 99 lines in 0.024001 secs.

In [12]:
graphlab.get_dependencies()


By running this function, you agree to the following licenses.

* libstdc++: https://gcc.gnu.org/onlinedocs/libstdc++/manual/license.html
* xz: http://git.tukaani.org/?p=xz.git;a=blob;f=COPYING
    
Extracting xz.
Extracting gcc-libs.
Copying gcc-libs into the installation directory.


In [4]:
data.head()


Columns:
	5.1	float
	0.222222222	float
	3.5	float
	0.625	float
	1.4	float
	0.06779661	float
	0.2	float
	0.041666667	float
	setosa	str

Rows: 10

Data:
+-----+-------------+-----+-------------+-----+-------------+-----+-------------+
| 5.1 | 0.222222222 | 3.5 |    0.625    | 1.4 |  0.06779661 | 0.2 | 0.041666667 |
+-----+-------------+-----+-------------+-----+-------------+-----+-------------+
| 4.9 | 0.166666667 | 3.0 | 0.416666667 | 1.4 |  0.06779661 | 0.2 | 0.041666667 |
| 4.7 | 0.111111111 | 3.2 |     0.5     | 1.3 | 0.050847458 | 0.2 | 0.041666667 |
| 4.6 | 0.083333333 | 3.1 | 0.458333333 | 1.5 | 0.084745763 | 0.2 | 0.041666667 |
| 5.0 | 0.194444444 | 3.6 | 0.666666667 | 1.4 |  0.06779661 | 0.2 | 0.041666667 |
| 5.4 | 0.305555556 | 3.9 | 0.791666667 | 1.7 | 0.118644068 | 0.4 |    0.125    |
| 4.6 | 0.083333333 | 3.4 | 0.583333333 | 1.4 |  0.06779661 | 0.3 | 0.083333333 |
| 5.0 | 0.194444444 | 3.4 | 0.583333333 | 1.5 | 0.084745763 | 0.2 | 0.041666667 |
| 4.4 | 0.027777778 | 2.9 |    0.375    | 1.4 |  0.06779661 | 0.2 | 0.041666667 |
| 4.9 | 0.166666667 | 3.1 | 0.458333333 | 1.5 | 0.084745763 | 0.1 |     0.01    |
| 5.4 | 0.305555556 | 3.7 | 0.708333333 | 1.5 | 0.084745763 | 0.2 | 0.041666667 |
+-----+-------------+-----+-------------+-----+-------------+-----+-------------+
+--------+
| setosa |
+--------+
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
+--------+
[10 rows x 9 columns]

In [7]:
data

Columns:
	5.1	float
	0.222222222	float
	3.5	float
	0.625	float
	1.4	float
	0.06779661	float
	0.2	float
	0.041666667	float
	setosa	str

Rows: 99

Data:
+-----+-------------+-----+-------------+-----+-------------+-----+-------------+
| 5.1 | 0.222222222 | 3.5 |    0.625    | 1.4 |  0.06779661 | 0.2 | 0.041666667 |
+-----+-------------+-----+-------------+-----+-------------+-----+-------------+
| 4.9 | 0.166666667 | 3.0 | 0.416666667 | 1.4 |  0.06779661 | 0.2 | 0.041666667 |
| 4.7 | 0.111111111 | 3.2 |     0.5     | 1.3 | 0.050847458 | 0.2 | 0.041666667 |
| 4.6 | 0.083333333 | 3.1 | 0.458333333 | 1.5 | 0.084745763 | 0.2 | 0.041666667 |
| 5.0 | 0.194444444 | 3.6 | 0.666666667 | 1.4 |  0.06779661 | 0.2 | 0.041666667 |
| 5.4 | 0.305555556 | 3.9 | 0.791666667 | 1.7 | 0.118644068 | 0.4 |    0.125    |
| 4.6 | 0.083333333 | 3.4 | 0.583333333 | 1.4 |  0.06779661 | 0.3 | 0.083333333 |
| 5.0 | 0.194444444 | 3.4 | 0.583333333 | 1.5 | 0.084745763 | 0.2 | 0.041666667 |
| 4.4 | 0.027777778 | 2.9 |    0.375    | 1.4 |  0.06779661 | 0.2 | 0.041666667 |
| 4.9 | 0.166666667 | 3.1 | 0.458333333 | 1.5 | 0.084745763 | 0.1 |     0.01    |
| 5.4 | 0.305555556 | 3.7 | 0.708333333 | 1.5 | 0.084745763 | 0.2 | 0.041666667 |
+-----+-------------+-----+-------------+-----+-------------+-----+-------------+
+--------+
| setosa |
+--------+
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
+--------+
[99 rows x 9 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [9]:
data.shape


(99, 9)

In [10]:
data.head(20)

Columns:
	5.1	float
	0.222222222	float
	3.5	float
	0.625	float
	1.4	float
	0.06779661	float
	0.2	float
	0.041666667	float
	setosa	str

Rows: 20

Data:
+-----+-------------+-----+-------------+-----+-------------+-----+-------------+
| 5.1 | 0.222222222 | 3.5 |    0.625    | 1.4 |  0.06779661 | 0.2 | 0.041666667 |
+-----+-------------+-----+-------------+-----+-------------+-----+-------------+
| 4.9 | 0.166666667 | 3.0 | 0.416666667 | 1.4 |  0.06779661 | 0.2 | 0.041666667 |
| 4.7 | 0.111111111 | 3.2 |     0.5     | 1.3 | 0.050847458 | 0.2 | 0.041666667 |
| 4.6 | 0.083333333 | 3.1 | 0.458333333 | 1.5 | 0.084745763 | 0.2 | 0.041666667 |
| 5.0 | 0.194444444 | 3.6 | 0.666666667 | 1.4 |  0.06779661 | 0.2 | 0.041666667 |
| 5.4 | 0.305555556 | 3.9 | 0.791666667 | 1.7 | 0.118644068 | 0.4 |    0.125    |
| 4.6 | 0.083333333 | 3.4 | 0.583333333 | 1.4 |  0.06779661 | 0.3 | 0.083333333 |
| 5.0 | 0.194444444 | 3.4 | 0.583333333 | 1.5 | 0.084745763 | 0.2 | 0.041666667 |
| 4.4 | 0.027777778 | 2.9 |    0.375    | 1.4 |  0.06779661 | 0.2 | 0.041666667 |
| 4.9 | 0.166666667 | 3.1 | 0.458333333 | 1.5 | 0.084745763 | 0.1 |     0.01    |
| 5.4 | 0.305555556 | 3.7 | 0.708333333 | 1.5 | 0.084745763 | 0.2 | 0.041666667 |
+-----+-------------+-----+-------------+-----+-------------+-----+-------------+
+--------+
| setosa |
+--------+
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
| setosa |
+--------+
[20 rows x 9 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

In [13]:
from sklearn import tree
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']

In [15]:
clf= tree.DecisionTreeClassifier()

In [16]:
clf=clf.fit(data,names)

TypeError: float() argument must be a string or a number